[pyprland]
plugins = ["menubar", "scratchpads", "fetch_client_menu", "layout_center"]

[menubar]
command = "waybar"
monitors = ["DP-1", "DP-2"]

[scratchpads.term]
animation = "fromBottom"
command = "foot -T footfloat"
class = "foot"
size = "80% 75%"
#max_size = "1920px 100%"
margin = 0
pinned = true
unfocus = "hide"
hysteresis = 0

[layout_center]
margin = 60
offset = [0, 30]
next = "movefocus r"
prev = "movefocus l"
next2 = "movefocus d"
prev2 = "movefocus u"
